services:
  db:
    image: mysql:8.0
    container_name: prestabanco-db
    restart: always
    environment:
      MYSQL_DATABASE: prestabanco_db
      MYSQL_USER: prestabanco_user
      MYSQL_PASSWORD: prestabanco_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - prestabanco-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./prestabanco
    container_name: prestabanco-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/prestabanco_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: prestabanco_user
      SPRING_DATASOURCE_PASSWORD: prestabanco_password
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - uploads_data:/app/uploads
    networks:
      - prestabanco-network

  frontend:
    build: ./front-end
    container_name: front-end-frontend
    restart: always
    depends_on:
    - backend
    ports:
    - "80:80"
    environment:
    - VITE_BACKEND_URL=http://localhost:8080
    networks:
    - prestabanco-network


volumes:
  db_data:
  uploads_data:

networks:
  prestabanco-network:
    driver: bridge
