pipeline{
    agent any
    stages{
        stage("Build Frontend"){
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/xshift007/presta_banco/']])
                dir("front-end"){
                    bat "npm install"
                    bat "npm run build"
                }
            }
        }
        stage("Set Docker Context") {
            steps {
                bat "docker context use default"
            }
        }

        stage("Build and Push Docker Image"){
            steps{
                dir("front-end"){
                    script{
                         withDockerRegistry(credentialsId: 'docker-credentials') {
                            bat "docker build -t xsh1ft/front-end ."
                            bat "docker push xsh1ft/front-end"
                        }
                    }
                }
            }
        }
    }
}
